doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            uuid_mariadb: App\Shared\Infrastructure\Doctrine\Type\UuidType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        mappings:
            RoomModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Room'
                prefix: 'App\Modules\Room'
                alias: Room

            SeatModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Room/Seat'
                prefix: 'App\Modules\Room\Seat'
                alias: Seat
            UserModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/User'
                prefix: 'App\Modules\User'
                alias: User
            ReservationModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Reservation'
                prefix: 'App\Modules\Reservation'
                alias: Reservation
            ScreeningModule:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Screening'
                prefix: 'App\Modules\Screening'
                alias: Screening
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
