services:
  cinema-nginx:
    image: nginx:stable-alpine
    depends_on:
      - cinema-php
    networks:
      - cinema-project
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  cinema-php:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - cinema-project

  cinema-db:
    image: mariadb:10.11.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cinema
      MYSQL_USER: cinema
      MYSQL_PASSWORD: cinema
      MYSQL_DATABASE: cinema_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cinema-project

networks:
  cinema-project:
    external: true

volumes:
  dbdata: ~
